<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TProjectSolution.DataAccess\TProjectSolution.DataAccess.csproj" />
    <ProjectReference Include="..\TProjectSolution.Entities\TProjectSolution.Entities.csproj" />
    <ProjectReference Include="..\TProjectSolution.Infrastructure\TProjectSolution.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
